### ISSUE TITLE
Installation Failure: unable to install integrated Python environment

### ISSUE THREAD

**Issue by DarkBroodBrews** [chaiNNer-org/chaiNNer#1042]
- Chainner version: 0.12.7 windows64
- OS: Windows 7 SP1, Python 3.8.10, home WiFi private network, no VPN

**Description**
Installation failure. Chainner has been granted full network access on both private and public networks.
 
"ChaiNNer was unable to install its integrated Python environment. Please ensure that your computer is connected to the internet and that chainner has access to the network."

Please advise.

**Comment by joeyballentine** [comment]
Windows 7 is officially not supported at this time due to integrated python being python 3.9, which as I'm sure you're aware of does not support Windows 7.

If you really want to attempt to use chaiNNer, you can try to manually change the use-system-python setting so it will use your python 3.8 installation. Go to `%appdata%/chaiNNer/settings`, make a new text file, name it `use-system-python` without a file extension (if the file already exists, just open it in notepad or something), and then edit the file to contain just the word `true`. 
More could definitely go wrong by using Windows 7 though. Everyone who has attempted to use 7 has had issues. 

Honestly, at this point you should just update to 10 at least. Windows 7 reached EOL quite a while ago.
