### ISSUE TITLE
Stable Diffusion

### ISSUE THREAD

**Issue by Devdens** [chaiNNer-org/chaiNNer#1155]
Is there a possibility of integration with Stable Diffusion? Generate images

**Comment by 0x4E69676874466F78** [comment]
That's in the plans.

**Comment by joeyballentine** [comment]
I want to add stable diffusion support, but since SD is still very new there isn't just one defacto codebase we can base our imenentation off of. It seems like there's new improvements and whatnot every day, plus lots of people being accused of stealing code. I'd rather just let all the dust settle first before we even touch it.

**Comment by Devdens** [comment]
> I want to add stable diffusion support, but since SD is still very new there isn't just one defacto codebase we can base our imenentation off of. It seems like there's new improvements and whatnot every day, plus lots of people being accused of stealing code. I'd rather just let all the dust settle first before we even touch it.

How do you like the option to use the API with https://beta.dreamstudio.ai/home ? Each user will enter their own token

**Comment by joeyballentine** [comment]
I'd rather have everything in chaiNNer run locally

**Comment by joeyballentine** [comment]
Would we consider this complete with the release of 0.18? Technically it is integrated now, just not internally. @RunDevelopment
