### ISSUE TITLE
Drag and drop model files with automatic creation of a node with the model

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [chaiNNer-org/chaiNNer#1196]
If I now try to drag a file (for example a pth) I get an warning:
![изображение](https://user-images.githubusercontent.com/4449851/200629812-40a6f4cd-5283-4171-b984-18e773767b19.png)
And I would like to get a node with a specified model.

**Comment by RunDevelopment** [comment]
Nice feature. 

Just two notes:
1. Implementing this be a little difficult because we have no guarantee that pytorch is installed. So the implementation must not assume that it can create Load Model nodes.
2. This should probably also work for other model types. Namely, NCNN .param/.bin and ONNX .onnx files should also work.
