### ISSUE TITLE
Is being flaged as malicius/malware

### ISSUE THREAD

**Issue by gustavoGazevedo** [chaiNNer-org/chaiNNer#1382]
Being flagged as malware by Hybrid Analysis: [overview](https://www.hybrid-analysis.com/sample/369cc931ee7bf57575758992a9d3f77461ae2f27629fb8158ccc3f5e5df0eff0)

Flagged as malicious by VirusTotal: [overview](https://www.virustotal.com/gui/file/369cc931ee7bf57575758992a9d3f77461ae2f27629fb8158ccc3f5e5df0eff0/detection)

**Comment by joeyballentine** [comment]
I mean, there's kinda nothing I can do about that... ChaiNNer is definitely not malicious but I can see how it would appear that way since we use subprocesses and download and install things at runtime. Once I have enough money saved up I'm planning on getting a signing certificate so hopefully at least windows will stop saying it could be dangerous. 

Also, the files that hybrid analysis are flagging as suspicious are just electron DLLs and Squirrel installer files (the .exe installer we uses, and that discord uses as well IIRC. It's pretty common for electron apps), so I think this website is just inaccurate.

Virtustotal only had 1 flag, so I don't think that's a big deal.

To be honest, I'm not really experienced enough to know what to do to make chaiNNer appear more trustworthy to these things. I think just by its nature of being a program that runs a python subprocess and installs dependencies automatically it just looks suspicious, and we aren't going to be changing anything about that.
