### ISSUE TITLE
Display decimals for whole number float inputs

### ISSUE THREAD

**Issue by theflyingzamboni** [chaiNNer-org/chaiNNer#1548]
Currently, when a float in a number input is a whole number, the frontend displays them as integers. This makes it unclear to users that number inputs like those in Box and Gaussian Blur support decimals. The number inputs that pair with sliders do not have this issue and always display their full precision.

**Comment by RunDevelopment** [comment]
The number input currently hides decimal zeros by default. We could probably change that so that it only hides decimal zeros when the precision is very large (e.g. the Math node uses precision=100).

That being said, I think we could do better with blur radii in general. Pretty much all image editors use sliders for radii, so we should probably do the same. We added log scale slider some time ago, so the user experience would be pretty good. 
The only problem is that we would have to define a fixed maximum radius. We could borrow a trick from Gimp here. Gimp sliders have 2 min/max values: one range for the sliders displayed in the UI, and another for the actually allowed values. So we could define max=1000 for the slider and max=inf for the logic actually enforcing it. So users can use sliders on the blur nodes, and if they need a radius larger than the slider's max, they can simply connect a number node to it.

**Comment by joeyballentine** [comment]
That sounds good to me

**Comment by RunDevelopment** [comment]
All blur nodes use sliders for some time now, so this isn't an issue anymore.
