### ISSUE TITLE
Extremely Slow Performance on Mac

### ISSUE THREAD

**Issue by fendrix69** [chaiNNer-org/chaiNNer#1549]
I was trying to use Chainner on a Mac, but it is pretty much unusable. I'm running it on a M1 Pro with 16GBs of RAM and 512GB SSD Drive. I was trying to upscale a 2K resolution image by a factor of 200% and after 30 minutes I had to kill the process. I tried several times. I also tried a bunch of models with the same results of my Mac getting either freezed or stuck in rendering mode. I rebooted my Mac and the whole computer seems irresponsive and slower now. 

How can I fully uninstall everything that the app has installed in my system, such as the Python Libraries and the FFmpeg components?

Thanks

**Comment by joeyballentine** [comment]
To fully uninstall everything including the python stuff, you'd need to delete the chaiNNer folder in Application Support.

However, I assume you're using CPU pytorch for this. That of course is going to be really slow. The version of pytoech we use doesn't support Mac GPUs. You would need to switch to system python and install via a terminal the latest version of pytorch in order to take advantage of the special apple support they added. Nobody has tested this so far, so I'm not actually sure if it works.

You also can convert pytorch models to NCNN, which at least will also use your Mac GPU, just not as well as the latest pytorch would. 

Feel free to uninstall, our Mac support and especially for M1s isn't great (i don't have a machine to test on unfortunately) but if you don't mind testing that out i would appreciate it :)

**Comment by RobBW** [comment]
Like @fendrix69, I am trying to use Chainner on a Mac M2 mini running Ventura.
I have so far been unsuccessful in getting PyTorch to run in MPS mode using an externally linked version of python 3.10.
I suggest part of that problem can be resolved by using the advice offered at [https://github.com/kritiksoman/GIMP-ML/issues/59](url) 
_"Avoid using .cuda() in order to implement Apple Metal MPS backend too. Use torch.device() instead"_

[https://github.com/ivvv](url) has applied these suggestions to GIMP3-ML with good results. 
See [https://github.com/ivvv/GIMP3-ML/tree/GIMP3-ML](url). 

I note that ChaiNNer code uses torch.cuda in a number of places but am uncertain how exactly to change them as suggested above. Is it a simple _find_ 'torch.cuda" and _replace_ with 'torch.device() ?

If you can guide me, I'm happy to try your suggestions and report back.

**Comment by joeyballentine** [comment]
We shouldn't be using .cuda anywhere, we specifically move it to the device stored in execution options, which for M1/2 devices should be MPS. 

https://github.com/chaiNNer-org/chaiNNer/blob/ba8012a53903b94d9b80d2d4452620acd7543364/backend/src/nodes/impl/pytorch/utils.py#L23

If that if statement isn't working though, that could explain it. I'm unable to test it myself to verify that the condition is valid.

If there are any extraneous .cuda calls, we definitely need to fix that. I'll check for any tomorrow

**Comment by RobBW** [comment]
Thanks for your quick response.
I have experimented more with ChaiNNer and have not been able to persuade it to work in anything but the "cpu" mode on my Mac M2. In "cpu" mode it takes 20 to 30 mins to get a result from a simple x2 SR upscale.
Regardless of what I do to the settings, the main.log shows "cpu" every time. I have separately tested for the presence of Torch running on "mps" using the following commands, each one of them shows True when run in Terminal:
print(hasattr(torch, "backends"))
print(hasattr(torch.backends, "mps"))
print(torch.backends.mps.is_built())
print(torch.backends.mps.is_available())

This suggests to me that the Line 23 setting you referred me to is either being overidden or ignored.

I attach main.log in case it can help you.
[main.log](https://github.com/chaiNNer-org/chaiNNer/files/10868947/main.log)

There is a memory issue which I think is unrelated, so I'm raising it separately.

**Comment by joeyballentine** [comment]
Based on that log, it looks like you are still using integrated python and not system python. Are you sure you have the setting enabled? 

If you do, then i think it's falling back to integrated because it either can't find your system python instance or there is some other issue with it (which doesn't seem to be logging) 

Since it's just using integrated python, it's on too old of s pytorch version to be able to use MPS.

**Comment by stonerl** [comment]
This issue should be resolved with v0.19.1.

MPS workes now.
