### ISSUE TITLE
v0.18.1 does not work on Windows 7

### ISSUE THREAD

**Issue by Reel-Deal** [chaiNNer-org/chaiNNer#1601]
When I try to use either v0.18.0 or v0.18.1 (portable) it does not work on Windows 7. I get this error:  ``The procedure entry point GetPackageFamilyName could not be located in the dynamic link library KERNEL32.dll.`` However, v0.17.1 works just fine.

**Comment by joeyballentine** [comment]
I believe this is due to the fact that we updated electron in 0.18 and electron ended support for windows 7. We never really officially supported windows 7 anyway due to some dependency issues people were having (as noted in the readme) so, I guess i should change that to just officially not supporting windows 7.

Also, FYI you're using an operating system that no longer gets security patches. Consider upgrading to 10 at least.

**Comment by Reel-Deal** [comment]
Thanks for the quick reply. I had downloaded chaiNNer less than a week ago and I got around the Python dependency by just placing the [api-ms-win-core-path-l1-1-0.dll](https://github.com/nalexandru/api-ms-win-core-path-HACK) in the Python folder and it worked fine. So right now that I tried updating to the latest version I discovered it no longer works.

Yeah I know, I actually have an unopened Win10 Pro disc that I bought some years ago. I may cave in since it is starting to become an uphill battle.
