### ISSUE TITLE
'Save Image' node can overlap Image Directory Iterator

### ISSUE THREAD

**Issue by Raecaug** [chaiNNer-org/chaiNNer#1731]
**Information:**

- Chainner version: 0.18.5
- OS: Windows 11
**Description**
It is possible for the save image node to extend outside the bounds of a directory iterator node, overlapping it.
As seen here:

![image](https://user-images.githubusercontent.com/23362597/231204577-903b47e2-618b-4edd-950a-4c3b57d22900.png)

**Comment by RunDevelopment** [comment]
That's a good find. Thank you for reporting @Raecaug!

I wonder what the indented behavior here is? Should we just relocate the child node to be in bounds, or should we extend the iterator's bounds? 

@joeyballentine What do we currently do and *why*?

Whatever is the correct behavior, we need to update the bounds of child nodes more often. Because of type conditions, we need to update the bounds of all child nodes with groups whenever the global type state changes. I say type state because it includes all inputs and output overrides (so we can capture the changing state of starting nodes (e.g. auto reloading Load Image)).

**Comment by joeyballentine** [comment]
I think the current correct behavior would be for it to be pushed in bounds, but i think I'd rather make it extend the iterator area instead if possible.

This reminds me: nodes can overflow out of an iterator when using snap to grid
