### ISSUE TITLE
Chainner update deleted all my *.chn files

### ISSUE THREAD

**Issue by avviano** [chaiNNer-org/chaiNNer#1756]
I updated to the new chainner via windows exe file. All my CHN files (and I had alot of them) are all wiped out now. Where are they????

**Comment by joeyballentine** [comment]
Where were you saving them to? Chainner should not have touched any directory other than it's installation location (which if i remember correctly is in appdata/local/chainner). If you were storing your chain files there, this is a life lesson not to store project files where a program is installed to. If not, I'm interested to know how this happened

**Comment by avviano** [comment]
I saved it in the folder that Chainner brings up by default when you click save. Which was appdata/local/chainner. When I started the installer, I saw all the contents in the folder disappear and then the new files re-appear. Although this is called an update, it did not just update or overwrite existing files, but wiped out the whole directory. It seems that there is a delete command in the installer, which make absolute zero sense. I now lost one week of work. Oh man....

**Comment by joeyballentine** [comment]
Well, this definitely highlights that the default directory it opens for that should not be appdata/local/chainner.

As for how it's updating, that's just the way the electron installer we use works. There's nothing i can do about that.

Sorry about your chn files, that really sucks. Afaik there isn't any way to recover those. I'll see about getting that default directory changed ASAP

**Comment by avviano** [comment]
Your installer should also prompt users and inform them before wiping it off their harddrives. Quit honestly, I never saw an app delete a folder for an update before. That is totally new to me... In theory, you just need to overwrite existing files, or install to a new version folder (like Adobe and most other apps do it - for exactly that reason). Deleting anything on users machine without prompting is not best practise.

**Comment by avviano** [comment]
Anyway, thank you for creating an awesome product. I am sure you will get it fixed. I will just have to cut my losses....

**Comment by joeyballentine** [comment]
I guarantee you nearly every other program on your computer updates in a similar way to this. How do you expect something to update if it's not replacing the original file? Yes patching exists but that's a lot more difficult of a process and is more prone to breaking. And if you're thinking "that can't be", you've just never noticed because you haven't been saving things to their application directories, and they don't prompt you before deleting either. 

As for prompting and informing users, I'd love to do that but i literally can't. I've tried so many different ways to prompt the user after an update is finished but literally nothing works. The installer we use is pretty garbage in that regard. 

Btw, it's the same installer Discord uses. It's called Squirrel. Feel free to look at whatever documentation related to how it updates you want. 

I get you're angry about this, but it's not like I made the intentional decision of making you save your files to a particular folder, and then programmed it to delete the files in that folder. You just discovered an unfortunate combination of the save window defaulting to the exe directory and the way the updater works.

Glad you like chaiNNer, and i hope it's not too much of a pain to recreate all your chains.

**Comment by avviano** [comment]
If it deletes the folder first, then its technically not an update / upgrade but a fresh install. Anyway, it seems that other users have had this issue with squirrel, which you can read here: 

https://github.com/Squirrel/Squirrel.Windows/issues/1630
