### ISSUE TITLE
Processing Nodes should be iterator-aware to improve performance

### ISSUE THREAD

**Issue by pokepress** [chaiNNer-org/chaiNNer#1769]
**Motivation**
Forgive me if this is a Dunning-Krueger red herring, but from looking at the code, it looks like there are places where we can improve efficiency by detecting if we're iterating over a set of files. Here's an example:

https://github.com/chaiNNer-org/chaiNNer/blob/1d44b10e4bab58ab2a41becbe916164cc419468a/backend/src/nodes/impl/pytorch/auto_split.py

**Description**
Based on the file above, it looks like we send both the model and the image to the device (CPU or GPU), which is fine if we have a single image we're processing, but if we're iterating over a series of images, we're most likely using the same model for the entire set, so we should only have to send it to the device once during the operation. Likewise for some of the cleanup operations. A model is often on the order of megabytes, so it's not inconsequential to repeatedly send it. There may also be benefits to things such as saving output files in a batch instead of individually.

**Alternatives**
I didn't see any pull requests that seemed to cover this idea.

As far as an implementation, perhaps nodes that take an image as input can discern whether they're being fed from the iterator's loading node, or observe that they're inside an iterator.

**Comment by RunDevelopment** [comment]
No, we are not doing anything like this right now.

It's an interesting idea. I wonder by how much this would improve performance. How fast/slow a model is to run basically scales with how large it is, so the models that would benefit from such an optimization, might be too slow for it to matter. E.g. saving 100ms on loading a model isn't much when the model takes 10s to run. So we should do some measuring on this.

**Comment by joeyballentine** [comment]
Honestly this sounds like something that can be improved across the board, not just in iterators. Images will have to be cast each time, that's inevitable. But if we start the chain off putting the model onto the correct device and in the right fp-mode, we shouldn't ever have to change it again unless settings get changed.

**Comment by joeyballentine** [comment]
Just did a quick comparison of removing those calls that move the model to the GPU again. 3m57 normally, 3m47 with them removed. That seems like it's within the margin of error, though I was doing this with a few large images rather than many small ones.

It's important to note that we _do_ put the model on the GPU when it's loaded, as well as putting it in the right precision mode. I think the only reason I also put the .device calls elsewhere was to avoid issues from settings changes, for example if you change which GPU you want to use, but the model was already loaded by the preview (and therefore cached). I guess I had previously assumed that doing .device when it was already on the device would not impact performance, but I will continue testing to see if that is really the case.

**Comment by joeyballentine** [comment]
Did another test with some smaller images. Somehow, it was faster having more of the calls. I don't really know how to explain that lol. Though, it could be margin of error still.

.device calls each iter:
17, 18, 17

just on load:
18, 18, 18

**Comment by RunDevelopment** [comment]
Oh, I was wrong. We are already doing this optimization, although not explicit for iterator, but just in general. Since the `.device` call in `pytorch_auto_split` is only for correctness, I think we can close this issue. Even removing this call, we were not able to measure a significant difference.
