### ISSUE TITLE
Setting the width in the Cropper to auto calculate

### ISSUE THREAD

**Issue by jeffreylm** [chaiNNer-org/chaiNNer#1800]
Good Day Everyone,

I was watching a tutorial about using crop offset, and the person said it is possible to have certain values calculated for you based on the dimention of the image.

My goal is to feed it a midjourney grid and have it do this for instance: TopOffset= width/2
So that I can get to the second quadrant of the image. 

I couldn't find documentation on this. Is there somewhere I can read about chainer settings/Channer manual?

Kind regards,
Jeffrey

**Comment by RunDevelopment** [comment]
You can use the Get Dimensions node to get the width, height, and number of channels of an image. The Math node can then be used to divide by 2. This can look like this in chainner:

![image](https://github.com/chaiNNer-org/chaiNNer/assets/20878432/7db501ae-9425-4240-b888-7df72b558e08)


> I couldn't find documentation on this.

Because we don't have any... Sorry.

**Comment by jeffreylm** [comment]
Hello Michael,

Really thank you for taking the time to make this screen grab for me. I just keep having to say that this application is insanely powerful.

Kind regards,
Jeffrey Levenstone

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by RunDevelopment** [comment]
I'm gonna close this now as the issue seems to have been resolved.
