### ISSUE TITLE
Output scale for Upscale Image node

### ISSUE THREAD

**Issue by MaxJa4** [chaiNNer-org/chaiNNer#1823]
**Motivation**
Usually, upscaler models have a 4x scale factor. If input images are e.g. already Full-HD and should be upscaled to 4k, it's a waste of time and computational resources to 4x them (8k in this example), only to scale them down to 2x again (so a 50% multiplier with the rescale node) - which is also an unnecessary extra step.

**Description**
I would appreciate an option - like already possible in the Upscale Face node - to specify the scale factor for image upscaling (between 1 and the model's typical scale).

This could look like this:
![image](https://github.com/chaiNNer-org/chaiNNer/assets/74194322/75eec6f1-b26c-4b78-9f63-89251eb01c6c)

I tried to implement it myself and had a look at different implementations of ESRGAN etc., but it wasn't as trivial as I hoped - looks like that one surpasses my knowledge, otherwise I'd have made a PR for it. Thanks!

**Comment by joeyballentine** [comment]
The scale of models is intrinsic to the model. If i added a scale option, all it would be doing is downscaling the resolution image for you. Any GUI that runs these models with a scale option is just doing that for you. There's no way to change the scale of a model like this.

The upscale face node only has that option (which just resizes it at the end) because the GFPGAN repo had that and i was trying to match functionality there. But i wasn't really happy about it and tbh, i kinda just want to remove that since it's misleading.

**Comment by MaxJa4** [comment]
Oh I see. I'm used to being able to set the scale in tools like stablediffusion-webui... there it also makes a big difference (time and resources) if you upscale to just 2x or e.g. the native 4x, hence my assumption, that the scale factor can be adjusted. But since there is a lot of other stuff going on, that may influence things.
Thanks. though!
