### ISSUE TITLE
Error  An error occurred in a Upscale Face node

### ISSUE THREAD

**Issue by ahmettetikci** [chaiNNer-org/chaiNNer#1940]
Error

An error occurred in a Upscale Face node:

Failed to run Face Upscale.

Input values (partial):
• Image: RGB image 7728x10304
• Upscaled Background: None
• Output Scale: 1x
• Weight: 0.7

**Comment by ahmettetikci** [comment]
can  any one help me ?

**Comment by joeyballentine** [comment]
1) what OS are you on
2) what GPU do you have 
3) does normal upscaling work?
4) is the face in the image obscured?

**Comment by ahmettetikci** [comment]
@joeyballentine  
I'm useing windows 10 - Amd Ryzen 7 2700X Eight -Core Processor 3.70 Ghz

Normal upscal work and face in the image not obscured.

**Comment by ahmettetikci** [comment]
And ı have 16 GB ram

**Comment by joeyballentine** [comment]
Can you send me the main.log file from Help > Open logs folder?

**Comment by ahmettetikci** [comment]
how can ı send it to you ?

**Comment by ahmettetikci** [comment]
@joeyballentine  https://drive.google.com/file/d/17A2fOOuCobfujr0_-nr7WLa4ChQYG5vm/view?usp=sharing

**Comment by joeyballentine** [comment]
You should be able to attach it to GitHub as a file attachment

**Comment by joeyballentine** [comment]
Ah ok, you are running out of VRAM when trying to upscale the face. Your options are to try to run it in CPU mode (can change in settings), or upscale a smaller image. (Or buy a better GPU, but that obviously isn't ideal)

**Comment by RunDevelopment** [comment]
> Input values (partial):
> • Image: RGB image 7728x10304

No wonder you were running out of VRAM. You would probably need like 32~64GB of VRAM for that... Are there even cards with that much...

Yeah, upscaling can be super memory intensive. I have 11GB of VRAM and the max image size I can upscale is around 1000x1000 px. (Sometimes more, sometimes less. Depends on the specific AI/upscaler.)

---

Anyway, I'm going to close the issue now, since it isn't a problem with chainner itself. Feel free to continue to comment in case we missed something or you have more questions.
