### ISSUE TITLE
ONNX with CoreML support for macOS

### ISSUE THREAD

**Issue by stonerl** [chaiNNer-org/chaiNNer#2013]
**Motivation**
Currently, when using ONNX on macOS, the only Execution Provider available is CPU. This is due to the limitations of the upstream project. 

**Description**
There is a developer who integrated the CoreML Backend into ONNX:

https://github.com/cansik/onnxruntime-silicon

Would you consider adding this version to chaiNNEr so that the macOS version would also have at least one backend that does offer hardware acceleration?

**Comment by joeyballentine** [comment]
Ok this is really interesting -- I just opened a PR to remove onnxruntime-silicon (#2010) because I thought it was just a package that built the arm64 wheels before the official package did (which I believe was the original intent of the project). We actually do currently use onnxruntime-silicon, so all we'd need to do to support it I guess would just be to use the coreml runtime by default.

Thank you for letting me know about this, I had no idea the dev added CoreML support. Gonna go change my PR now.

**Comment by joeyballentine** [comment]
Closing this as it seems coreml support for onnx is too underdeveloped to make this a useful feature
