### ISSUE TITLE
strange results with error diffusion algorithms

### ISSUE THREAD

**Issue by simolg** [chaiNNer-org/chaiNNer#2037]
**Information:**

- Chainner version: 0.19.0
- OS: Windows 10

**Description**
Strange areas are visible when reducing an image to very few colors;
this error occurs with all diffusion maps, **only Atkinson works well** (perhaps for its particular matrix)

I attach for example an image converted to 8 colors using each maps
![Dithering_test](https://github.com/chaiNNer-org/chaiNNer/assets/103586111/af68f204-9f53-442c-a50e-83e1bbdf82f7)

**Comment by RunDevelopment** [comment]
Interesting. I have used the Dither node before and haven't seen such artifacts. Could you please provide the original image, so we can reproduce the bug?

**Comment by simolg** [comment]
![Akira_600x500](https://github.com/chaiNNer-org/chaiNNer/assets/103586111/2b396a8c-0f88-4b82-aeae-b2304f5afbb6)

I used this palette, but the problem is visible with many other palettes :
![pal08_MagicWB](https://github.com/chaiNNer-org/chaiNNer/assets/103586111/9ee8e3e6-8dcc-48ca-86ed-d6f1f11534c9)

these are my chainNner settings :
![chaiNNer_error_diffusion](https://github.com/chaiNNer-org/chaiNNer/assets/103586111/46d2d355-5d88-4f56-a259-42c1c4eaece9)

I'm also studying the problem but my python knowledge is limited
thank you very much, chaiNNer is an amazing program :)

**Comment by RunDevelopment** [comment]
Okay, I think I figured out what is going on. I think the issue is your color palette. 

The basic idea of [error diffusion](https://en.wikipedia.org/wiki/Error_diffusion) is to pick the nearest color for a given pixel, calculate the error (difference between the nearest color and the color we want), and then we add this error onto neighboring pixels. 

So what would happen if we never find a good nearest color for some color in the image? The error would just keep on accumulating until we find some other color in the image where we can reduce the error again. This is what is happening here. Your color palette does not include a good red, so diffusion algorithms like F&S will keep accumulating the error. That's the orange "shadow" you see under the bike and under Akira.

So why does Atkinson not have this issue? Atkinson is unique among our diffusion algorithms in that it only diffuses 75% of the error. This means that the diffused error accumulates more slowly, and that it is quickly reduced to reasonable levels again once we leave the region with the problematic color (here red).

Or to put it another way: the issue is that you are effectively using the color palette to remap colors/do tone mapping. This is not what dithering is intended to do, so the results are weird.

**Comment by simolg** [comment]
Yes, I had the same thought too, Atkinson Dithering is the only one that propagates only a fraction of the error
( in truth all algorithms propagate fractions of the error, seeing the maps . . . )

I have read with interest:
https://tannerhelland.com/2012/12/28/dithering-eleven-algorithms-source-code.html
https://en.wikipedia.org/wiki/Floyd%E2%80%93Steinberg_dithering

But all other programs with the same image and palette give different results, here an example (with : Floyd–Steinberg)
![Akira_600x500_Floyd–Steinberg](https://github.com/chaiNNer-org/chaiNNer/assets/103586111/260c5bd3-f0e4-4dc5-9e5d-df9b032d6530)

My suspicion is that there is an error in the calculation of the distance of the colors and this error is gradually being carried forward ( in the example image the affected area is almost white, yet you can see a red spot )

I'm focusing on this code:
`backend/src/nodes/impl/dithering/color_distance.py`

**Comment by RunDevelopment** [comment]
> in truth all algorithms propagate fractions of the error, seeing the maps

Those fractions add up to 100%. Atkinson is the only one where they add up to only 75%.

> But all other programs with the same image and palette give different results

What other programs? If they (or their dither effect) are/is open source, I could look at how they do it.

> My suspicion is that there is an error in the calculation of the distance of the colors and this error is gradually being carried forward

That was my suspicion too. The color distance code is frankly more complex, than it needs to be, but the gist of it is this: we use a KD-tree to find the nearest color. "Near" is here defined as the Euclidean distance of the channels of 2 colors. This seems okay to me. I wanted to try out other distance functions, but unfortunately OpenCV doesn't support other distance functions. We can scale channels, but that's about it.

That being said, I want to re-implement the dither node algorithms in Rust for performance reasons eventually (dithering is possible in real time, and chainner needs multiple seconds to do it...). I already picked out a good KD-tree library that supports more distance functions for something else. So we don't have to restrain ourselves to what OpenCV supports, we have options.

**Comment by simolg** [comment]
The last image provided was made with DPaint-js:
https://www.stef.be/dpaint

code that processes the color reduction:
https://github.com/steffest/DPaint-js/blob/master/_script/util/imageProcessing.js

other portal where I made the comparisons, you can provide image, desired colors and algorithms:
https://doodad.dev/dither-me-this/

hope it's helpful

**Comment by RunDevelopment** [comment]
Sorry for the delay, I was busy re-implementing the dither algorithms in Rust. This makes them about 100 times faster, and gives us more control, since we don't have to rely on OpenCV for performance anymore.

I fixed this issue by doing `clamp(color + error, 1, 0)` just like DPaint-js. While this does mean that we lose some detail (since the error isn't diffused perfectly), that's a small price to pay. Here's the result we get now:

![image](https://github.com/chaiNNer-org/chaiNNer/assets/20878432/4d81dfe0-55ce-4d77-85c6-94020f00d8b6)
![image](https://github.com/chaiNNer-org/chaiNNer/assets/20878432/6b144742-85ff-4a6c-80dc-a23064a0e369)

This is pretty much identical to the result we get from DPaint-js.

I'll make a PR for this the coming days, so it will part of the next release.

**Comment by RunDevelopment** [comment]
Looks even better with gamma correction: 
![image](https://github.com/chaiNNer-org/chaiNNer/assets/20878432/7e8bd5a8-223c-4965-b080-75a1ec57e827)
