### ISSUE TITLE
Video File Iterator

### ISSUE THREAD

**Issue by Agroithien** [chaiNNer-org/chaiNNer#2063]
**Motivation**
I have multiple low quality videos I need to upscale them.

**Description**
Just like "Image File Iterator" I need "Video File Iterator " so that it can be automated.

**Alternatives**
I know I can make 1 big video out of small clips by joining them in a video editor but It's a long process.

Thank you...

**Comment by joeyballentine** [comment]
This probably won't happen until our iterator rewrite since this would end up being a double loop. Maybe we could do something in the meantime like make the video frame iterator allow taking a directory as well as a file, but we'll see. 

I want to avoid making all sorts of different iterators, for one because it'll make it harder to eventually convert them to our new system whenever that happens, and two because it'll just give us less motivation to actually make that system happen. But I also don't like missing nice functionality, so I'm a bit torn.

**Comment by Agroithien** [comment]
I understand, I'll just combine small videos and make a big one and then do it... Thank you for this software and Thank you for your hard work..................................(*・‿・)ノ⌒*:･ﾟ✧
