### ISSUE TITLE
Set compression level for PNG

### ISSUE THREAD

**Issue by stonerl** [chaiNNer-org/chaiNNer#2186]
Currently, saving a PNG only allows the color depth to be set. Usually, PNG can have a compression level ranging from 0 (no compression) to 9 (highest compression).

It would be nice to have this option.

**Comment by RunDevelopment** [comment]
Careful here. OpenCV is weird about PNG compression levels. See [this comment](https://github.com/chaiNNer-org/chaiNNer/issues/251#issuecomment-1130485038) for numbers.

The issue is the following: OpenCV uses libpng under the hood. libpng is very complex and under-documented software, so nobody want to mess with more than they have to. The folks at OpenCV are the same. So what does OpenCV do to save PNGs? Black magic. Or something similar...

So PNG compression largely has 2 parameters that determine the speed vs compression tradeoff. (1) Compression level basically says how hard LZW will try, and (2) filters determine what data LZW will see. Filters try to reframe the image data in a way that makes it more compressible. The PNG spec basically just defines a bunch of filters and then tells encoders to somehow pick the best combination of filters. This is a slow process since you have to basically brute force your way through. Try out all filters, see how well they do individually, pick the best combination. The more filters you have, the slower it is.

So what does OpenCV do? When you manually set a compression level, it will give that compression level to libpng and enable all filters. When you don't specify a compression level, it will tell libpng to use only a few filters + compression level 3-ish.
They do this because few filters + low compression level is waaay faster than all filters + compression level=0.

This fucky details makes it really hard to add a sensible PNG compression level to Save Image. If you add it as a simple slider (0-9), then you just made saving PNGs worse for all users. Compression level=0 is slower than no specified compression level and produces larger files. Of course, everything >0 is even slower.

The issue is that OpenCV makes a really smart tradeoff between speed and compression that we can't replicate with a simple compression level slider.

**Comment by stonerl** [comment]
Interesting. Gonna close this on, since witchcraft shouldn't be part of chaiNNer 😆
