### ISSUE TITLE
DiffBIR upscaling

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [chaiNNer-org/chaiNNer#2191]
https://github.com/XPixelGroup/DiffBIR
for info

**Comment by joeyballentine** [comment]
This one would be much more work to implement due to a few things 
1) chkpt files mean we need torch lightning as a dependency 
2) needs xformers as well as a dependency 
3) it's a two stage model, which might not make a difference but could make it more complicated depending on how that's laid out in the state dict 

But I can potentially look into it soon... Maybe.

**Comment by adegerard** [comment]
Made some tests on real/cartoon images, not so good (euphemism) except on the images they use as examples! (worse than SCUnet)
and so many dependencies...

**Comment by 0x4E69676874466F78** [comment]
@joeyballentine well, I found this, so I thought I'd share it, that it might be an interesting solution (I didn't test it, I took it on faith), but judging by adegerard's reply it turned out not to be a good solution, sorry.

**Comment by joeyballentine** [comment]
I was also told this rehires 40GB of VRAM to run on a 512x512 image, and that is really unrealistic for actual use. Maybe someday, but yeah this probably won't be implemented any time soon
