### ISSUE TITLE
If the file exists in the destination folder, skip to the next one.

### ISSUE THREAD

**Issue by w8prouser** [chaiNNer-org/chaiNNer#2230]
**Motivation**
I do bulk conversion of texture files from old games and I always have some problem with the power here, the PC shuts down, then I lose the sequence of edited files with those that will still be modified, then need to do tiger ballet to get back where I left off.

**Description**
I request, if possible, that the app has a file identifier function in the destination folder, if the file of the same name already exists, that it skip to the next one.

**Alternatives**
That alone would be of great help.

**Comment by joeyballentine** [comment]
As much as I'd really like to have something like this, it's not entirely possible, or at the very least not trivial. Since you can have whatever nodes in between the load and save steps, there is no way to 100% guarantee we can know the file name ahead of time and skip processing it. We can skip saving it, sure, but only once all the other processing has happened.

Maybe in the future with iterator filters or something we could have nodes that would let you filter out input names if the same names are in the output directory, but you'd have to be saving with the same names for that to even work.

Anwyay, TLDR; I'd love to, but we can't. At least not right now

**Comment by RunDevelopment** [comment]
Fixed by #2808.

This feature is available in versions v0.23.2 and up.
