### ISSUE TITLE
System PIP option doesn't appear to work

### ISSUE THREAD

**Issue by aaronliu0130** [chaiNNer-org/chaiNNer#2231]
**Information:**

- Chainner version: e.g. 0.20.1
- OS: Windows 11 Insider Dev 25951

**Description**
![image](https://github.com/chaiNNer-org/chaiNNer/assets/11874211/0c13850c-aa72-47f2-82cd-f26adb112b86)
Nothing appears to happen when I flip the switch. Switch resets when I restart chaiNNer. Was working in 0.19.4.

**Logs**
[why doesn't github support 7z's](https://github.com/chaiNNer-org/chaiNNer/files/12654023/logs.zip)

**Comment by joeyballentine** [comment]
Ok so the reason this is happening is because an old version of numba is currently cached on your system. I recommend purging your pip cache completely and this should start working. You aren't the first person this has happened to, so I guess I need to make chaiNNer ignore pip caches. I belueve it says how to clear the cache here: https://pip.pypa.io/en/stable/cli/pip_cache/

**Comment by aaronliu0130** [comment]
Still won't work...
[logs.zip](https://github.com/chaiNNer-org/chaiNNer/files/12654142/logs.zip)

**Comment by joeyballentine** [comment]
Is it still just erroring when you try install the onnx dependencies?

**Comment by aaronliu0130** [comment]
There's no error, it just straight up uses the integrated even after I flip the switch.
[logs.zip](https://github.com/chaiNNer-org/chaiNNer/files/12666397/logs.zip)

**Comment by joeyballentine** [comment]
Ah, I think I understand your confusion now. That's not the same as using system python. That setting is located in the settings view under the python tab. "Use pip directly" is just a bypass for something we do to track download progress of the whl files, where it won't download using pip. That toggle just bypasses that to run the install command entirely through pip if you're having issues otherwise. If you just wanna use your system python, change the actual setting

**Comment by aaronliu0130** [comment]
Ah... silly me
