### ISSUE TITLE
deps installing freezing and terrible performance

### ISSUE THREAD

**Issue by hooke007** [chaiNNer-org/chaiNNer#2318]
**Information:**

- Chainner version: latest release & [nightly](https://github.com/chaiNNer-org/chaiNNer-nightly/releases/tag/2023-11-04)
- OS:  Windows 10

**Description**
When i try to reinstall chaiNNer, it was always blocked at the step of downloading pytorch. And then I can hear my fans of cpu/gpu shouting.

![Snipaste_2023-11-07_12-02-22](https://github.com/chaiNNer-org/chaiNNer/assets/41094733/5162779a-7a4b-4c09-9883-d9ceedb8588d)

![Snipaste_2023-11-07_12-01-58](https://github.com/chaiNNer-org/chaiNNer/assets/41094733/e118f941-dfc2-4f37-9ad7-976996effb0d)

![Snipaste_2023-11-07_12-02-11](https://github.com/chaiNNer-org/chaiNNer/assets/41094733/3aa06c60-f046-4bf8-b8f5-f9270649c3e9)

**Logs**

[main.log](https://github.com/chaiNNer-org/chaiNNer/files/13275597/main.log)
[renderer.log](https://github.com/chaiNNer-org/chaiNNer/files/13275598/renderer.log)

**Comment by hooke007** [comment]
`use pip directly` is the available workaround.

**Comment by joeyballentine** [comment]
Yep thats exactly what use pip directly is for, when the regular one doesnt work. That being said, this is a good reminder that i still gotta update this to track progress in a better way, that would prevent the original issue from happening again

**Comment by lostcowboy** [comment]
This is my third time trying to get dependencies installed twice with the  chaiNNer-0.20.2-windows-setup.exe  and the last time with  chaiNNer-windows-x64-0.20.2.zip The first time and I think the second time it stopped downloading somewhere during the PyTorch (4 packages) download. just sat there with spinning wheels On the second attempt I even left it overnight and yes I did try the use PiP Directly with no luck. I used the wise uninstaller and totally uninstalled it. On the third try, I used the zip file hoping that was the portable version, it also timed out on downloading the dependencies. I restarted once again, switched to Pip Directly, and tried to complete it again. This time it seemed to remember what it had already downloaded and did not try and download all 4 of the PyThon packages again, I think it is completed now.
My suggestion is to completely download all dependencies before installing them. Busy servers like to drop connections that are not downloading. I think your Dependency Manager downloads and installs each package and then gets the next one, somewhere in there the server that you are getting the packages from drops the connection, and your manager is expecting to have a connection and does not try to reconnect, that's why you get the spinning wheels.
 [main.log](https://github.com/chaiNNer-org/chaiNNer/files/13734635/main.log)
[renderer.log](https://github.com/chaiNNer-org/chaiNNer/files/13734637/renderer.log)

The reason I was hoping for a portable install is I have a small C drive that is almost full and I am trying not to install large programs on it.

**Comment by joeyballentine** [comment]
If you were using the use pip directly option, then it installs through pip, and therefore exactly the same as installing to python normally, and is not managed by chaiNNer. If that's not working, then it's not something wrong with chaiNNer. Are you able to install pytorch to your system python via running the pip install command in your terminal?

**Comment by jonathancolledge** [comment]
I have this problem too. I got it working before by just closing ChaiNNer and trying again multiple times. Now I'm trying the nightly build and the same thing happens - eventually I have NCNN and ONNX installed, just stuck on Pytorch. PIP didn't work, but I know the normal way works eventually so I will keep trying. 

It would be great to download the required files in a browser (which seems to cope better with interruptions in connection) and then install from those downloaded files. 

Interestingly, I have this same problem with stable diffusion. My internet is mobile and so varies a lot from a few kbps (slower than old dial up) to 500 mbps. The ping is also very long 1000 ms or so. I think downloads just timeout or something. This has been a problem with a third app, which I can't remember and I just downloaded the files with my browser.

**Comment by joeyballentine** [comment]
This gave me an idea, which is to put a button in that would launch the command in an external terminal window. That not only would help eliminate issues but also show people exactly what they'd need to run to get the deps installed.

We could perhaps also have a mode that opens the download url in a browser once it parses it from pip, but the issue with that is that then the user would need to know what command to run afterwards to install it

**Comment by RunDevelopment** [comment]
> `use pip directly` is the available workaround.

Since we basically always do that now, I think the issue can be closed now. If the normal installation process doesn't work, users can also easily manually install packages now.
