### ISSUE TITLE
Pytorch Upscale Image node tiling issue

### ISSUE THREAD

**Issue by Darkenlord1** [chaiNNer-org/chaiNNer#2461]
**Information:**

- Chainner version: [0.21.0]
- OS: [Windows 10]

**Description**
Trying to simple process images through model, however, with tile set to anything lower than 4096 it gives errors at some large images. Workflow preview attached.
![image](https://github.com/chaiNNer-org/chaiNNer/assets/20936024/94843ffc-f03b-4970-84ac-510488be2fab)

**Logs**
Error log from interface:
```
Error

An error occurred in a pytorch Upscale Image node:



Input values:
• Image: RGB Image 3900x4680
• Model: Value of type 'spandrel.__helpers.model_descriptor.ImageModelDescriptor'
• Tile Size: Auto (estimate)
• Separate Alpha: No
```
[logs.zip](https://github.com/chaiNNer-org/chaiNNer/files/13928974/logs.zip)

**Comment by joeyballentine** [comment]
Thanks for reporting and for providing logs. Definitely looks like there's something wrong with the tiling code there. The issue is that the end result tile does not match the size we would expect. We will look into it.

**Comment by Darkenlord1** [comment]
And also with 4096 too, if image larger than that, it fails.

```
Error

An error occurred in a pytorch Upscale Image node:



Input values:
• Image: RGB Image 3900x4678
• Model: Value of type 'spandrel.__helpers.model_descriptor.ImageModelDescriptor'
• Tile Size: 4096
• Separate Alpha: No
```

**Comment by RunDevelopment** [comment]
Found the issue. It's specific to ESRGAN models, kinda. So the issue is that the image size you have results in awkward tile sizes. In particular, it results in tiles with an odd width or height. It seems that, 1x and 2x ESRGAN models do not like that, and always output images with even sizes. E.g. if you give it a 5x16px image, it will return a 8x16px image.

In my testing, output image sizes are always a multiple of 4 (rounded up). So 1x ESRGAN models change the output size the most, and 4x models don't change it at all.

The reason we are only seeing this bug now is that the new tiling code strictly enforces the assumptions it makes about tiles. So the issue isn't with the tiling code, but the upscaling code and spandrel.
