### ISSUE TITLE
Clear field context menu option

### ISSUE THREAD

**Issue by terrainer** [chaiNNer-org/chaiNNer#2521]
**Motivation**
This is a QoL feature that could be useful. If you try to delete a folder containing a model file that's loaded in chaiNNer, Windows will say you don't have permissions. If this is intentional, a quick way to clear the loaded model (rather than loading another model, deleting the node, or closing the program entirely) would come in handy.

**Description**
Implementation could be either an "x" button inside the Model field, next to the loaded model name, or right click > clear.

**Alternatives**
Another solution is to just allow the deletion of the files, then display a file not found error in chaiNNer.

**Comment by terrainer** [comment]
I'm realising this isn't a consistent issue, so I'm not sure what causes the file permissions error.

**Comment by joeyballentine** [comment]
> Windows will say you don't have permissions. If this is intentional,

It's not intentional per se, but it's a side-effect of the fact that chaiNNer watches each file you pick for changes so it can auto-reload if it does. I guess this means that Windows considers the file "in use"

As for being able to clear an individual input, that's a great idea that i'm surprised we hadn't already added. We do have a clear option when you right click on the node itself, but not the input. thanks for the suggestion!

**Comment by RunDevelopment** [comment]
I think Joey's guess is that wrong, and that what happened was simply PyTorch trying to load the model at the same time you were trying to remove it. The file watcher we use explicitly does **not** mark the file as "in use" preventing deletion. Aside from the fact that a file watching that locks files is useless (since no one could modify those files), file watchers are implemented by either hooking into OS APIs for file watching or by repeatedly pulling lstat, and neither would lock a file. The file watcher cannot be the cause of this issue.

> As for being able to clear an individual input, that's a great idea that i'm surprised we hadn't already added. 

This option only really makes sense for certain inputs without a default value. E.g. try "clearing" a checkbox or a slider. I think it would be enough to only have this option for file and directory inputs for now.
