### ISSUE TITLE
Add a "Flush cache and restart" option 

### ISSUE THREAD

**Issue by mrjschulte** [chaiNNer-org/chaiNNer#2537]
Sometimes you just want to have a clean slate. Adding a "Flush cache and reset option" button in the chaiNNer preferences would be really helpful at times when you've messed up your dependencies of caches.

**Comment by RunDevelopment** [comment]
Could you please describe this a bit more? I have no idea what you mean by "clean slate" and "dependencies of caches".

**Comment by mrjschulte** [comment]
I tend to develop in separate directory setups and fresh/clean git pulls for every feature branch. Immediately followed by npm i to set up that instance of the chaiNNer dev space I use. 

Sometimes I play with adding new deps and mess things up so it would be great to be able to wipe out all of the installed Python dependencies with a npm reset or similar command so I don't have to port my work to a new structure on my end. 

And I fully acknowledge I'm out of the usual "this is how this should be used/work world" :)

**Comment by RunDevelopment** [comment]
> wipe out all of the installed Python dependencies

Python dependencies are installed globally by default. So removing all of them is probably not what you want since `pip` (the package installer) is also a package/dependency.

Installing more python deps than necessary also typically doesn't mess anything up, so I'm not sure what problems you ran into to require resetting all dependencies.

> I tend to develop in separate directory setups and fresh/clean git pulls for every feature branch. Immediately followed by npm i to set up that instance of the chaiNNer dev space I use.

That sounds painful.

As for my usual development workflow: I use feature branches and just commit my current state whenever I want to switch between branches. (We squash PRs into a single commit anyway, so having a messy commit history is fine.) Since the backend and the frontend automatically refresh with `npm run dev`, switching between branches is pretty seamless. So you can have chainner open, switch to another branch, and the app will refresh to show you the state of that branch.

That's also how I test PRs btw. I just checkout the PR branch like any other branch and play around with it.

**Comment by mrjschulte** [comment]
ok, this is a great insight. Also about how all sub-commits get squashed to make the history clean.
