### ISSUE TITLE
The program does not Upscale.

### ISSUE THREAD

**Issue by Gushla** [chaiNNer-org/chaiNNer#2730]
I downloaded Chainner in version 18.9, used it for a while and left it. When I came back, I updated the program and tried to upscale it as I did before, but there is no difference in the result. Only the number of resolutions increases, no improvement in the photo. I use 4x.pth.

- Chainner version: [22.2]
- OS: [Windows 11]

**Comment by RunDevelopment** [comment]
Could you please provide for more information? Right now, I do not know what your issue is nor how to reproduce it.

> tried to upscale it as I did before

Did you load an old chain or did you create a new chain in the node editor? Could you show us a screenshot of the chain you used (menu: File > Export viewport as PNG)?

> Only the number of resolutions increases, no improvement in the photo.

So the output image was larger. What does "no improvement" mean?

> I use 4x.pth.

This unfortunately doesn't tell us which model you used. Could you provide a link to where you got the model? The issue might be that the model is bad.

**Comment by Gushla** [comment]
Thanks for your reply, I mean, I could tell the difference when I used it before, it was really upscale. I am attaching the images.
![chain](https://github.com/chaiNNer-org/chaiNNer/assets/140684708/beb6777a-f6f3-4087-88b4-4f265f99cfd2)
![size](https://github.com/chaiNNer-org/chaiNNer/assets/140684708/e45bb3a3-88c1-4771-b244-4e408eb0f556)
![SCALE](https://github.com/chaiNNer-org/chaiNNer/assets/140684708/0251acb5-c264-4383-999e-9632c90e4ae6)

**Comment by RunDevelopment** [comment]
This might just be the case of a bad model. It seems like you're using [BSDeviance](https://openmodeldb.info/models/4x-BS-Deviance), so I would suggest using a different model like [UltraSharp](https://openmodeldb.info/models/4x-UltraSharp).

**Comment by Gushla** [comment]
The model I was using preserved the artwork colors very well while upscaling, the one you recommended worked better, but the colors are shifting. I think I need to do some research on this and find something new. Thank you.

**Comment by RunDevelopment** [comment]
> but the colors are shifting.

Try using the Average Color Fix node. If the color shift isn't too bad, this node can probably fix it. 
(Quick start for ACF: The reference image is your original image, just leave the scale factor as is.)

**Comment by Gushla** [comment]
Yes, I got a better result, thank you.
