### ISSUE TITLE
Confusing and very limited conditional nodes capability

### ISSUE THREAD

**Issue by Potato22** [chaiNNer-org/chaiNNer#2982]
Apologies if none of this made too much sense, I'm no expert on this. Feel free to correct or ask for clarification, I'll try my best.

**Motivation**
While trying to make an automation to check if the image resolution is above my specified threshold that switches the upscaling multiplier to either `1` or `4` - I realized how limiting the conditional node is. There is no easy way to create even slightly advanced logic conditions.  

![image](https://github.com/chaiNNer-org/chaiNNer/assets/39096741/162be771-f771-456b-8c1a-98a6a70e5628)

(All of this to create an XOR)  
The documentation is very not helpful, all it gave was what it expects from input and what it spits out at output.  
  

**Description**
There needs to be an easier way and give finer control for more advanced conditional scenarios  
  
I'm thinking of:
- Adding logic operators as their own nodes. (AND, ANDOR, OR, XOR, NOT, etc)
- Even better if the Conditional node can handle an "else if" condition that expects a new logic rule.  

**Alternatives**
The only workaround is the screenshot above. Even then that only accepts 2 values, inevitably it will need even more nodes to accept more values.
![image](https://github.com/chaiNNer-org/chaiNNer/assets/39096741/523922ac-afaa-4ea8-9444-00cfc7cf4c7c)

**Comment by joeyballentine** [comment]
Good callout on needing a node for logic operators. That shouldn't be too hard to implement and is definitely necessary 👍

As for else if, that really can just be handled by using another node. Since there's no way of knowing how many conditions + else ifs someone would need, the "right" way of implementing that in a nodular system is just using as many nodes as you need, even if it doesn't look clean.
