### ISSUE TITLE
Additional pytorch conversion support

### ISSUE THREAD

**Issue by jhitz0z** [chaiNNer-org/chaiNNer#2993]
![Screenshot 2024-07-12 110253](https://github.com/user-attachments/assets/34354a74-6812-4f60-abef-bddb20c82f28)

**Description**
May you add some addition support for -Compact,DAT,HAT,SPAN,Realplksr,SwinIR,SRFormer,GRL,RGT,  Architecture for NCNN and ONNX conversions.

**Comment by joeyballentine** [comment]
This isn't unsupported because we haven't done something necessary. It's unsupported because NCNN doesn't support it. That is not something I can do anything about.

**Comment by jhitz0z** [comment]
What's the NCNN repo?

**Comment by joeyballentine** [comment]
https://github.com/Tencent/ncnn

But, that doesn't matter that much because chaiNNer uses my fork of NCNN that added back in the Vulkan support they disabled for the python bindings. I also had changed a couple other things to have better error handling. The official NCNN is way more up to date now (though I still don't think they've added the ops required to be able to convert these models), but I can't update my fork easily due to conflicts. And while I could spend the time to figure that stuff out, for me NCNN is so low priority I'd rather just remove it from chaiNNer entirely than do anything else with it, to be honest. 

If someone can figure out how to get chaiNNer moved over to the official package, that would be really cool. But I tried myself and just got errors, so I don't think it's possible.

**Comment by jhitz0z** [comment]
Ah, that's unfortunate. Regardless, thanks for letting me know.
