### ISSUE TITLE
Upscale Image node's size changes

### ISSUE THREAD

**Issue by RunDevelopment** [chaiNNer-org/chaiNNer#712]
The output label "Upscale Image" is quite long, so the type tag widens the node.

![image](https://user-images.githubusercontent.com/20878432/183447255-d39b3da3-3a42-4309-ab06-31c5deb6f863.png)

**Comment by joeyballentine** [comment]
This is more of a general problem that I've seen happen to other nodes, and it's going to continue to be an issue.

We either need to just deal with the fact that nodes can change size depending on what information gets added, or we need to make each node unreasonably large just in case they have big labels and type tags, which I think is a bit ridiculous and a waste of space. 

That being said though, I think nodes should probably be at least as big as the width that having a text/number input makes them, since those nodes are typically wider

**Comment by joeyballentine** [comment]
Also, "upscaled image" can probably be changed to "result". I only did it that way since we didn't have any way of knowing the type in the olden days, so I wanted to include the word image

**Comment by theflyingzamboni** [comment]
I would just call them "Image" to make the Upscale nodes consistent with most of the other nodes. There are a few where we do things like specify what channels are input/output, but most nodes just say "Image".

**Comment by RunDevelopment** [comment]
Fixed by #2111.
