### ISSUE TITLE
Reload starting nodes

### ISSUE THREAD

**Issue by RunDevelopment** [chaiNNer-org/chaiNNer#732]
We currently run and cache starting nodes. However, this caching assumes that any files referenced by the node input data do not change.

Add a way for users to refresh the starting nodes, so that the cached output is up-to-date. This could either be a simple context menu entry "Refresh" or some kind of auto reloading (which would be nice).

**Comment by joeyballentine** [comment]
How would we do auto reloading?

**Comment by RunDevelopment** [comment]
I think [fs watchers](https://www.geeksforgeeks.org/node-js-fs-watch-method/) would be the easiest way.

**Comment by joeyballentine** [comment]
Does that just constantly try to load the file? or does it do something smart to make it take almost no performance

**Comment by RunDevelopment** [comment]
It's smart. OSes have a built-in functionality for this, and `fs.watch` API just exposes it to us.

**Comment by joeyballentine** [comment]
In that case, I think we should do that. A manual reload would be nice as well

**Comment by joeyballentine** [comment]
So I attempted to implement this. I don't think it's quite as possible as you think. I had to use a jank workaround in order to even get it to register that the inputData changed (by setting it to undefined, using a ref to store the previous value, then on change if it was undefined set it to the ref value). Also, the preview won't update since it registers that the input data is the same as the last run.

So, this is going to require some sort of rethinking as to how we want to implement this.
