### ISSUE TITLE
critical error - failed to fetch with ChaiNNER 0.11.1 on Mac OS 10.14.6 Mojave

### ISSUE THREAD

**Issue by predmunds** [chaiNNer-org/chaiNNer#752]
"chaiNNer  - has encountered a critical error - failed to fetch" error message.

I clicked "allow" network collection.
After downloading app components and loading dependencies etc
A screen opened with an error message.
<img width="630" alt="Screenshot 2022-08-18 at 16 32 41" src="https://user-images.githubusercontent.com/111522998/185440799-23378f99-041e-49b1-8bfa-2218f74e6808.png">

**Comment by joeyballentine** [comment]
Hi. We are currently getting a lot of reports from Mac users about issues. We are trying to figure out what exactly is going wrong. If you could please followil the advice listed here about sharing your logs, it would be greatly appreciated: https://github.com/joeyballentine/chaiNNer/issues/747#issuecomment-1219389230

**Comment by predmunds** [comment]
hi Joey. I didnt see any advice about logs - can you please point me to it? I just joined github to post the issue so its all new to me  . thanks, P

**Comment by RunDevelopment** [comment]
Joey meant this part:

>  In chainner's menu, click _Help_ > _Open logs folder_, create a zip with `main.log` and `renderer.log`, and [attach the zip file to a comment](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files).
>
> **Privacy information**: These log files contain file paths of chainner's files. The file paths may contain the name of your account (e.g. `Users/michael/...`). If your account is your real name, and you are not comfortable sharing, then do not upload your logs.

**Comment by predmunds** [comment]
Thanks RD. Can you please let me know where you copied and pasted that text from? I haven’t seen any of that guidance. Is it under a menu here on GitHub?

**Comment by RunDevelopment** [comment]
No, it's in [the issue comment Joey linked](https://github.com/joeyballentine/chaiNNer/issues/747#issuecomment-1219389230).

> I haven’t seen any of that guidance.

What do you mean by "guidance"? Do you mean [our README project page](https://github.com/joeyballentine/chaiNNer#chainner)? I'm asking because if we know where people look for stuff like this, we might as well put it there.

**Comment by joeyballentine** [comment]
> Thanks RD. Can you please let me know where you copied and pasted that text from? I haven’t seen any of that guidance. Is it under a menu here on GitHub?

I linked the comment at the end of mine

**Comment by joeyballentine** [comment]
@predmunds, could you please try the [latest release](https://github.com/joeyballentine/chaiNNer/releases/tag/v0.11.2) and see if it resolves your issues?

**Comment by joeyballentine** [comment]
Update on this issue btw: We can't support macos versions lower than 10.15 at the moment due to a critical dependency we need (opencv-python) not supporting < 10.15 yet. Their next update should support it (I worked out the problem with them), but they are taking a long time to release an update. So, eventually older macos versions _might_  work, but at this time we do not officially support them. I am going to close this issue as it is something that is currently out of my control. Just stay tuned for an update that mentions theoretical older macos support, and I will also try to find all the old issues and make comments about it when it happens.

**Comment by joeyballentine** [comment]
As of recent, opencv updated with <10.15 support. If you're still willing, could you give it a try?

**Comment by joeyballentine** [comment]
According to users who have tested it, macos < 10.15 still doesn't work. I will just officially say that it will never be supported.
