### ISSUE TITLE
Onboard rembg for image background removal

### ISSUE THREAD

**Issue by db0** [chaiNNer-org/chaiNNer#818]
**Motivation**
I want to be able to remove image backgrounds as part of my processing.

**Description**
[The rembg python module](https://github.com/danielgatis/rembg) uses a pytorch model to remove image backgrounds. It's not perfect but it's really damn good. I would like to have an option to use it during processing

**Comment by RunDevelopment** [comment]
> [!! This library is for Python 3.9 only !!](https://github.com/danielgatis/rembg#installation)

This might be a problem, since we support more than just 3.9. 

@joeyballentine Honestly, this seems like the perfect third-party module (narrow in scope, self-contained, could be a single node). If we include it into Chainner, then we should make it an official third-party module as soon as we have an API (#786).

**Comment by joeyballentine** [comment]
No need to add a third party library that only supports python 3.9 if you can just run the models already

**Comment by db0** [comment]
Sorry I am just not advanced enough for this usage. I'll see if I can figure it out myself, but in the meantime, it would still be cool if the chaiNNer module for this existed by default.

**Comment by joeyballentine** [comment]
My main point is that we might be able to support this without needing to add this dependency. If there's something specific about the models I'd be able to detect, I could add support for it (if it doesn't already just work) like I do for pytorch with all the models there

**Comment by theflyingzamboni** [comment]
Looking at it, it looks like it does things aside from just running the models, much like that Armory thing.

**Comment by theflyingzamboni** [comment]
@db0 Have you been able to make this package work? I pip installed it, but importing the module completely breaks opencv for me. Like, the moment I add a line importing it, cv2 functions no longer do anything. The interpreter skips the command, and a script just hangs.

**Comment by 0x4E69676874466F78** [comment]
Doesn't seem to need special support.
But model requires 320px tiles.
When I try to set this size I get an error.
```
[ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: input.1 for the following indices
 index: 2 Got: 163 Expected: 320
 index: 3 Got: 163 Expected: 320
 Please fix either the inputs or the model.

Input values (partial):
• Image: RGB image 1080x1080
• Tile Size Target: 320
```
But in general, the model works:
![image](https://user-images.githubusercontent.com/4449851/186896456-2da54d8b-e7de-406c-acdd-e9cba204b3eb.png)

**Comment by db0** [comment]
@theflyingzamboni you mean rembg in isolation? yes I use it a lot

**Comment by joeyballentine** [comment]
> When I try to set this size I get an error.

Tile size target isn't a real tile size. it's a workaround I did to be able to manually set the splitting depth the upscale function uses, without having it be confusing to anyone who knows what a tile size is. It basically converts the tile size into whatever split depth would get you the largest size under the target size. I will be changing how this works soon to be a bit more verbose, and later modifying it to be an actual traditional tile size.

**Comment by 0x4E69676874466F78** [comment]
This model requires the same patch as armorlab.
`in_nc -> 3`
We clearly need support for such models, this is the second such one.

**Comment by 0x4E69676874466F78** [comment]
I also did not understand what to do with the tiles. How to transfer tiles required size that is required for these models?

**Comment by joeyballentine** [comment]
@0x4E69676874466F78 if you're referring to the new "number of tiles" dropdown, that's basically just the same thing as a tile size only it's splitting the image into equal-size tiles, the number of which is chosen with that dropdown. (the only reason it's like this is because I'm reusing my automatic splitting code, but with manually chosen splitting. I'll eventually change this, it just requires me to write a normal tile size algorithm and I'm procrastinating on that)

So, you don't need a tile iterator. I guess we currently don't support models with static width and height, unless you know ahead of time what the width and height it needs is, in which case you could manually crop. I'll have to do something to detect those static dimensions and basically just make it ignore any tile size setting passed in.

**Comment by 0x4E69676874466F78** [comment]
@joeyballentine 
In theory, for static tile sizes, you need to complement the image size to a multiple of it.
Example: 320 tile size. Image 1024х1024 add border frame to 1280‬x1280‬ and autocrop after.

**Comment by theflyingzamboni** [comment]
@db0 I don't know if you got a notification when this issue was closed, but I got around to adding this to chaiNNer. It's not in a release version yet, but is available in [chaiNNer nightly](https://github.com/chaiNNer-org/chaiNNer-nightly).

**Comment by db0** [comment]
Yes I did indeed see it thanks for letting me know. Unfortunately I'm very busy with the ai horde atm so I can't test it. But great job nonetheless!
